apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
      - name: sample-node-app
        # Assuming you've tagged and pushed your image to the local registry
        # Replace 'localhost:5000' with your local registry's address if different
        image: localhost:5000/sample-node-app
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: sample-node-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: sample-node-app

